import {client as sanityClient } from "./client";
import { createGroqBuilder, makeSafeQueryRunner } from 'groqd';

// 👇 Import Sanity types, generated by your Sanity project.
import type * as SanityTypes from "./sanity.types";

// 👇 Create a type-safe query runner
export const runQuery = makeSafeQueryRunner((query, options) => {
  const { parameters, ...fetchOptions } = options ?? {};
  return sanityClient.fetch(query, parameters, fetchOptions);
});

// 👇 Create a type-safe query builder
type SchemaConfig = {
  schemaTypes: SanityTypes.AllSanitySchemaTypes
  referenceSymbol: typeof SanityTypes.internalGroqTypeReferenceTo;
};
export const q = createGroqBuilder<SchemaConfig>({});
